### ISSUE TITLE
Drop dependency on lodash.padstart

### ISSUE THREAD

**Issue by dolmen** [xbpf/gtin#18]
A dependency on an external module for [a 6 lines function](https://github.com/lodash/lodash/blob/4.6.1-npm-packages/lodash.padstart/index.js#L544)? Seriously...

**Comment by SEAPUNK** [comment]
Didn't particularly feel like waiting on `String.padStart` to land in Node.js back when I made this module. Feel free to open a PR if you feel strongly about this.
