### ISSUE TITLE
Updating to ES6

### ISSUE THREAD

**Issue by ajmas** [xbpf/gtin#19]
Would you be interested in updating this project to use ES6 conventions?

**Comment by SEAPUNK** [comment]
Sure. PRs welcome.

**Comment by SEAPUNK** [comment]
I might actually take a few hours to do this myself, I'll let you know if I've made progress or not.

**Comment by SEAPUNK** [comment]
Should be covered with the latest commits on master. Published v1.0.0 which includes Typescript support and more consistently named API.
