### ISSUE TITLE
Clarify that isGTIN does not validate the code

### ISSUE THREAD

**Issue by SEAPUNK** [xbpf/gtin#5]

**Comment by dolmen** [comment]
Could you give an example to reproduce your issue?

**Comment by SEAPUNK** [comment]
`isGTIN` just makes sure that the code provided looks like a GTIN, but doesn't actually check whether the code is valid: https://github.com/xbpf/gtin/blob/master/lib/index.js#L9

`validate` is what actually makes sure that the [check digit](https://en.wikipedia.org/wiki/Check_digit) is correct: https://github.com/xbpf/gtin/blob/master/lib/index.js#L17
